### ISSUE TITLE
Missing license or authorization label

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/image_batch_privacypreserver#1]
We have included this new chapters in the guide:
 - [Labels](https://github.com/chaimeleon-eu/workstation-images#labels)
 - [Description, usage and license](https://github.com/chaimeleon-eu/workstation-images#description-usage-and-license)

As this repository is private and it has not license, then you should include al least the label "Authorization".
(If you don't agree with the text or you think is better to reformulate please tell us.)

The other labels and sections in the _README.md_ file are optional but recommended.

**Comment by Palollo** [comment]
We've seen that you changed the visibility of the repository to Public and added the chapter "License" in the Readme.md with a link to a MIT license. 
Now the image is built and uploaded to the CHAIMELEON repository.

Just one more recommendation:
In the section "License" of the Readme.md, you should link to your own license file, not to the license of other repository. You can add your own easily as explained [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by XiaodanXing** [comment]
The license has been updated.

**Comment by Palollo** [comment]
You have added the license as a "Pull Request": #3 
You must merge the pull request to apply the changes.
